# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: blog.r0kithax.com
# email: your-email@example.com
description: Posts about infosec, bug bounties, and hacking techniques
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: r0kithax
github_username:  r0kit

# Build settings
markdown: kramdown
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.20.2"

# Minimal Mistakes specific settings
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "en-US"
subtitle:
name: "blog.r0kithax.com"
description: "Blogging about ethical hacking."
url: "https://blog.r0kithax.com"
repository: "r0kit/r0kit.github.io"
logo:
paginate: 10
search: true

author:
  name: "r0kit"
  avatar: "/assets/images/avatar.png"
  bio: "Pentester, researcher, bug hunter, infosec streamer, CTF player"
  location: "Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/r0kit"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/r0kithax"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/r0kit"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/UCjjPQZM-DNqCNbcLkFkYprQ/videos"
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discord.gg/wbPXa9B"
    - label: "Medium"
      icon: "fab fa-medium"
      url: "https://medium.com/@r0kit"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/r0kit"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/r0kithax"

# Enable default liquid categories and tags
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Default styling
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      share: true
      related: true
      author_profile: true
      layout: single
      classes: wide

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# The plugins below are safe to use with GitHub Pages using the --safe option 
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Extra file processing
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Compression
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
